server:
  port: 8766

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    api-r:
      path: /api-r/**
      serviceId: service-ribbon
    api-f:
      path: /api-f/**
      serviceId: service-feign